name: commands test

on: 
  push:
    branches: 
      - main

jobs: 
  command_test:
    runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3
       - uses: actions/setup-node@v2
         with: 
          node-version: 12
       - uses: actions/setup-python@v4
          with:
            python-version: '3.5'
  
       - run: npm ci
       - run: python test/test.py
